on: [push, pull_request]

name: ci

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: python -m pip install --upgrade pip
    - run: python -m pip install .
    - run: >
        python -c 'import logging, sys, shellingham;
        logging.basicConfig(stream=sys.stderr, level=0, force=True);
        shell = shellingham.detect_shell();
        print(shell);
        print(shell.pid)'

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: python -m pip install --upgrade pip
    - run: python -m pip install .
    - run: >
        python -c 'import logging, sys, shellingham;
        logging.basicConfig(stream=sys.stderr, level=0, force=True);
        shell = shellingham.detect_shell();
        print(shell);
        print(shell.pid)'
